name: qiskit_vqe_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - matplotlib
  - ipykernel  
  - pip:
      - qiskit>=1.0.0
      - qiskit-aer>=0.14.0
      - qiskit-algorithms>=0.3.0
      - pylatexenc  